### ISSUE TITLE
minor suggestion to improve the default prompt

### ISSUE THREAD

**Issue by nathanbraun** [chhoumann/bunnai#2]
Not really an issue persay but one one thing I've found that helps improve the quality of commit messages is adding this under instructions:

-   Keep in mind you will suggest 10 commit messages. Only 1 will be used. It's better to push yourself (esp to synthesize to a higher level) and maybe wrong about some of the 10 commits because only one needs to be good. I'm looking for your best *best* commit, not the best average commit. It's better to cover more scenarios than include a lot of overlap.

Cheers!

**Comment by chhoumann** [comment]
Hey @nathanbraun, thank you for the enhancement! I've added it to the default prompt :)
